services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=sahuagin
      - TZ=America/Los_Angeles
    ports:
      - "5432:5432"
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/postgres:/var/lib/postgresql/data