services:
  dolt:
    container_name: dolt
    environment:
      - DOLT_ROOT_HOST=%
      - DOLT_ROOT_PASSWORD=test
      - TZ=America/Los_Angeles
    expose:
      - "3306"
    image: dolthub/dolt-sql-server:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/dolt:/var/lib/dolt
