services:
  mariadb:
    container_name: mariadb
    environment:
      - MARIADB_ROOT_HOST=%
      - MARIADB_ROOT_PASSWORD=test
      - TZ=America/Los_Angeles
    ports:
      - "3306:3306"
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/mariadb:/var/lib/mysql
