x-gpu-service: &allow-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]
  ulimits:
    memlock:
      soft: -1
      hard: -1
    stack:
      soft: 67108864
      hard: 67108864

services:
  sahuagin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sahuagin
    environment:
      - DEBUG=True
      - TZ=America/Los_Angeles
    ports:
      - '9229:9229' # wasm-debug
    restart: unless-stopped
    volumes:
      - ./bind-mounts/files:/files
    <<: *allow-gpu
  dolt:
    container_name: dolt
    environment:
      - DOLT_ROOT_HOST=%
      - DOLT_ROOT_PASSWORD=test
      - TZ=America/Los_Angeles
    expose:
      - "3306"
    image: dolthub/dolt-sql-server:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/dolt:/var/lib/dolt
