services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    command: [ "/bin/sh" ]
    container_name: sahuagin-devcontainer
    hostname: sahuagin-devcontainer
    ports:
      - "50000:5432"
      - "50001:8888"
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace
      - ../docker-data:/var/lib/docker
      - ~/.ssh:/tmp/.ssh:ro
