x-gpu-service: &allow-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]
  ulimits:
    memlock:
      soft: -1
      hard: -1
    stack:
      soft: 67108864
      hard: 67108864

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    command: [ "/bin/sh" ]
    container_name: sahuagin-devcontainer
    hostname: sahuagin-devcontainer
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace
      - ../docker-data:/var/lib/docker
      - ~/.ssh:/tmp/.ssh:ro
    <<: *allow-gpu
