FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl git gpg apt-transport-https sed coreutils sudo openssh-client \
    postgresql postgresql-contrib pgcli \
    && rm -rf /var/lib/apt/lists/*

COPY poststart.sh /usr/local/bin/poststart.sh
RUN chmod +x /usr/local/bin/poststart.sh

CMD ["bash"]
