name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      build:
        context: .
        dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          pytest -v
