name: Publish Docker Image on Tag

on:
  push:
    # Trigger only on tags that match 'vX.Y.Z' (e.g. v1.2.3)
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # We fetch the full history to ensure we can properly read any tags/commits we need
          fetch-depth: 0

      # 2. Extract version from the tag name
      - name: Extract Version
        id: version
        run: |
          # GITHUB_REF might look like "refs/tags/v1.2.3"
          # Remove everything up to "v" to get "1.2.3"
          VERSION="${GITHUB_REF#refs/tags/v}"

          echo "Version found: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 3. Log in to Docker Hub (uses secrets DOCKER_USERNAME, DOCKER_PASSWORD)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          # Tag the image with both the version and "latest"
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sahuagin:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/sahuagin:latest
